services:
  - type: web
    name: resume-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: resume-frontend
    env: node
    rootDir: rbuild
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: rbuild/dist
